- name: Working with Vault
  hosts: localhost
  become: true
  vars_files:
          - vault-pass.yml
  tasks:
    - name: Clone Repo
      git:
            repo: https://{{ guser }}:{{ gpasswd }}@github.com/MuraliKarre/Newone.git
            dest: $WORKSPACE
      #shell: git clone https://{{ guser }}:{{ gpasswd }}@github.com/MuraliKarre/Newone.git
