- name: Working with Vault
  hosts: localhost
  become: true
  vars_files:
          - vault-pass.yml
  tasks:
    - name: Clone Repo
      git:
            repo: https://{{ guser }}:{{ gpasswd }}@github.com/MuraliKarre/Newone.git
            dest: /root/git
       tags:
          - git
      #shell: git clone https://{{ guser }}:{{ gpasswd }}@github.com/MuraliKarre/Newone.git
    - name:
      shell: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      tags:
          - docker 
